### ISSUE TITLE
Saving HAS_MANY with 'through' option

### ISSUE THREAD

**Issue by thomasmery** [yiiext/with-related-behavior#13]
Hi there,

thanks a lot for this extension!

I was wondering if there were any plans to implement saving HAS_MANY relations 'through' another relation

http://www.yiiframework.com/doc/guide/1.1/en/database.arr#relational-query-with-through

I don't think it is supposed to work for this case right now,

I would try myself at it but I  might not really grasp the inner working of Yii well enough to code something satisfactory

**Comment by creocoder** [comment]
It is not advisable. For saving optimally use natural relations. In next releases with-related-behavior will throw an exception while trying to save relation with `through` option.

**Comment by thomasmery** [comment]
would you try to explain why, even if briefly?

thank you

On Mon, Mar 26, 2012 at 2:19 PM, Alexander Kochetov <
reply@reply.github.com

> wrote:
> 
> It is not advisable. For saving optimally use natural relations. In next
> releases with-related-behavior will throw an exception while trying to save
> relation with `through` option.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/yiiext/with-related-behavior/issues/13#issuecomment-4692835

## 

---

## http://www.thomas-mery.net

**Comment by creocoder** [comment]
This option was introduced for the purpose of select. Also check CHANGELOG to see who has implemented the option ;-)

**Comment by thomasmery** [comment]
you mean the Yii changelog right?

**Comment by creocoder** [comment]
Yes, Enh #1117
