### ISSUE TITLE
accessing data into the intermediate table

### ISSUE THREAD

**Issue by manuel-84** [yiiext/with-related-behavior#15]
it would be nice if it will be possibile to access data into the intermediate (join) table

**Comment by creocoder** [comment]
Explain more

**Comment by manuel-84** [comment]
I'd like to do something like:

foreach($post->tags as $tag) echo $tag->jointableproperty

This is the problem: http://www.yiiframework.com/wiki/285/accessing-data-in-a-join-table-with-the-related-models/

Currently this is not possible in Yii with a MANY_MANY relation and it would be nice to do something like:

$post->withRelated->find('joinmodel')->jointableproperty

**Comment by creocoder** [comment]
Check framework manual about `through` relation option. It was possible at least year ago.
