### ISSUE TITLE
Cannot remove many-to-many relations when updating

### ISSUE THREAD

**Issue by flesheatingarthropods** [yiiext/with-related-behavior#17]
Hi,

I'm trying to manage many-to-many relations with the withRelations behavior. My problem is that the behavior successfully adds new relations on save and on update, but that I can't seem to remove relations on update.

I don't really know what I'm doing wrong - below are the relevant bits of code, maybe you can help me a little here.

Thank you for your time,

Eike

Relation in model

``` php
[....]
public function relations()
{
    return array(            
        'regions' => array(self::MANY_MANY, 'Region', 'brand_region_assignment(brand_id, region_id)'),      
    );
}
[....]
```

Controller  :

``` php
public function actionUpdate($id)
{
    [....]
        if(isset($_POST['Brandcheck']['countries']) && is_array($_POST['Brandcheck']['countries'])) {
            // the $_POST contains PKs for region models which we now retrieve
            $model->regions = Region::model()->findAllByPk($_POST['Brandcheck']['countries']);
        } else {
            $model->regions = array();
        }

        if($model->withRelated->save(true,array('regions'))) {          
            $this->redirect(array('index'));
        }
    [....]          
}
```

Edit: I had a look into the mysql log. It seems that on update the relations I want to remove are first deleted and then immediatly added back:

``` sql
 144 Query     DELETE FROM `brand_region_assignment` WHERE (`brand_region_assignment`.`brand_id`, `brand_region_assignment`.`region_id`) IN ((10, 9), (10, 15))
 144 Query     INSERT INTO `brand_region_assignment` (`brand_id`, `region_id`) VALUES (10, 9)
  144 Query     INSERT INTO `brand_region_assignment` (`brand_id`, `region_id`) VALUES (10, 15)
```

So this is perhaps a bug rather than me doing something wrong ?

**Comment by manuel-84** [comment]
What if I want to remove a specific record instead of all?

**Comment by Narretz** [comment]
When you read the other issues, you will find out that the extension only handles create & update, but not delete.

Also, I have a similar issue where I don't know if you can actually set existing relations to an arbitrary value:
$model->relations will return the relation data when it is set, and you cannot magically set it to something different. It appears to be get only.

**Comment by creocoder** [comment]
Update does not imply any removal. Use any indirect logic in beforeUpdate().
