### ISSUE TITLE
Bulk Insert

### ISSUE THREAD

**Issue by creocoder** [yiiext/with-related-behavior#18]
Use bulk inserts for DBMS that support this feature.

**Comment by creocoder** [comment]
Delayed until DAO will have such functional.

**Comment by samdark** [comment]
Are you going to work on the related pull request for Yii anytime soon?

**Comment by creocoder** [comment]
Started 3 month ago: https://github.com/yiisoft/yii/pull/1617

**Comment by samdark** [comment]
I mean if you're going to finish it? It says it's WIP still.

**Comment by creocoder** [comment]
Will continue to work on this next week.
