### ISSUE TITLE
Missing commits

### ISSUE THREAD

**Issue by rinatio** [yiiext/with-related-behavior#19]
Hey guys, we are using this extension as git submodule and for some reason get

fatal: reference is not a tree: 6243f6bf10b05f328060f4822eeb2e1277c4848f
Unable to checkout '6243f6bf10b05f328060f4822eeb2e1277c4848f' in submodule path 'protected/extensions/wr'

while checking out.

**Comment by robregonm** [comment]
I also use this extension as a submodule with no problems...
Make sure you are adding the module with: git submodule add URL_OF_REPO ./local/Url/Where/IWant/ToUse
For updating the submodule I use:
git submodule foreach --recursive 'git checkout master; git pull --verbose'
Hope this helps

**Comment by cebe** [comment]
@mashingan as you can see github linked your commit, so it exists in repo. make sure to do a git fetch inside submodule to get all commits in.

**Comment by rinatio** [comment]
@cebe I saw it exists in the repo, but it doesn't exists in commit history, does it?
It was working fine before last commit 40da8bc939fb36faf9481d6334ae3799d67823c6.
Try this for example:

```
git clone git://github.com/yiiext/with-related-behavior.git
cd with-related-behavior/
git checkout -b test 6243f6bf10b05f328060f4822eeb2e1277c4848f
```

Looks like someone changed commit history or have done --force push. That's not good idea.
I know it's not an issues of extension itself, i would write message to author, if github has message tool.

**Comment by cebe** [comment]
so this commit might got deleted from master branch then.
Go and check out latest master.

**Comment by rinatio** [comment]
@cebe Already fixed that, my point is: don't change commit history when it's already pushed to the repo.

**Comment by cebe** [comment]
@mashingan sure, should not be done, don't know who did it and why. @creocoder you might have the answer to this?

**Comment by creocoder** [comment]
@cebe Will not change commit history in future. Thanks.
