### ISSUE TITLE
документация раздел "Модель User"

### ISSUE THREAD

**Issue by yupe** [yiiext/with-related-behavior#2]
<?php
class User extends CActiveRecord
{
    /**
     \* @var integer id
     \* @var string username
     \* @var string password
     \* @var string email
     */
    ...
    public function behaviors()
    {
        return array(
            'profile'=>array(self::HAS_ONE,'Profile','user_id'),
        );
    }
    ...
}

Метод behaviors ? Не relations ?

**Comment by svyatov** [comment]
Да, скорее всего там должно быть relations...
