### ISSUE TITLE
Error saving a many_many relation

### ISSUE THREAD

**Issue by manuel-84** [yiiext/with-related-behavior#25]
I have other many to many relations where this extension is working good, but with this one I'm getting a fatal error

The situation:

in the model Event I have

``` php
'users' => array(self::MANY_MANY, 'User', 'tbl_user_event(event_id, user_id)'),
```

in the model User I have

``` php
'events' => array(self::MANY_MANY, 'Event', 'tbl_user_event(user_id, event_id)'),
```

in a controller when I need to save the relation I have

``` php
$userModel->withRelated->save(false, array('events'))
```

or

``` php
$eventModel->withRelated->save(false, array('users'))
```

The output:

Invalid argument supplied for foreach() @ WithRelatedBehavior.php:365

I'm using the last stable yii 1.1.13

**Comment by manuel-84** [comment]
Debugging a bit I've found that $related=$owner->getRelated($name); (line 205) is returning the string "2"

**Comment by cebe** [comment]
Guess you have `$userModel->users = '2';` or maybe a mass assignment to `'users'` before the save in your code.

**Comment by manuel-84** [comment]
+1 cebe
thanks, my stupid error due to migration from another similar extension (ESaveRelatedBehavior)
