### ISSUE TITLE
MANY_MANY dosen't work

### ISSUE THREAD

**Issue by cherifGsoul** [yiiext/with-related-behavior#3]
With MANY_MANY dosen't work for me i did as the exemple in the readme file you can find my schema [here](http://pastebin.com/eAgAurZk)

**Comment by cherifGsoul** [comment]
I tested with the form only for post and tags, I have a checkbox list for my tags,

<pre><code>
public function actionCreate()
    {
        $model=new Article;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Article']))
        {
            $model->attributes=$_POST['Article'];
            if($model->withRelated->save(true,array('tags')))
                $this->redirect(array('view','id'=>$model->id));
            
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

</code></pre>

**Comment by creocoder** [comment]
See unit tests. The same situation. All works.

**Comment by ghost** [comment]
The test works for me too, but when i use forms it seems not work

**Comment by cherifGsoul** [comment]
it's me on "yiisite". The test works for me too, but when i use forms it seems not work

**Comment by creocoder** [comment]
I didn't see you assign tags in your form example. There should be something like $article->posts=array(...);

**Comment by cherifGsoul** [comment]
ok thanks i will try to resolve it ;)
