### ISSUE TITLE
поддержка справочника в MULTI_MULTI

### ISSUE THREAD

**Issue by grikdotnet** [yiiext/with-related-behavior#4]
Привет, я тут пытался заюзать этот экстеншн для связи Multi-Multi, и не разобрался что делать чтобы использовать записи из таблицы-справочника.
Когда я просто делаю with->save(), он делает повторные insert-ы в справочник, а не юзает существующие значения из него.
Что я делаю неправильно?

Схема базы самая обычная, модели сгенерированы gii, обычным образом все работает.

**Comment by creocoder** [comment]
Приведите пример кода при котором происходят повторные insert-ы.

**Comment by grikdotnet** [comment]
проблема немного иная, чем я описал вначале

у меня 3 таблицы: `subscribers`, `categories` и таблица-связь
`subscribers_categories`
FK выставлены в базе, модели сгенерированы

я получаю информацию о подписчиках и делаю обновления связей между
подписчиками и категориями

``` php
$S = Subscribers::model()->find($Criteria);
if ($S){
   //запись есть, очистим старые данные
   SubscribersCategories::model()->deleteAll('subscriber_id=:s',array(':s'=>$S->id));
}else{
   //запись не найдена, создаем
   $S = new Subscribers;
}
$S->attributes = $data;

$categories = array();
foreach ($cats as $category) {
   $C = Categories::model()->find('name=:n',array(':n'=>$category));
   if (!$C){
       $C = new Categories();
       $C->name = $category;
   }
   $categories[] = $C;
   //я не могу написать $S->categories[] = $C; !
}
$S->categories = $categories;
$S->withRelated->save(true,array('categories'));
```

Если категории уже существуют, то данные подписчиков обновляются, но
записи в subscribers_categories не появятся.
Если нужных категорий нет, все записи создаются.

Если я вместо $C = Categories::model()->find всегда делаю $C = new Categories();
то записи в связке создаются, но дублируются записи в categories.

**Comment by creocoder** [comment]
Проблема подтверждается. Будет исправлена в ближайшее время.

**Comment by creocoder** [comment]
Fixed

**Comment by RusAlex** [comment]
как то можно коммитами закрывать тикеты. чтобы можно  было видеть в  текущем тикете соответствующий патч

**Comment by creocoder** [comment]
Спасибо за информацию, если возможность подтвердится, будем в следующий раз её использовать.
