### ISSUE TITLE
its still useless

### ISSUE THREAD

**Issue by blendsoft** [yiiext/with-related-behavior#6]
Updating relations does not  work, 
for example 

$post->tags=array();
$post->withRelated->save(true,array('tags'));

sholud clear all relations.

**Comment by allain** [comment]
I have fixed that in my fork.

**Comment by creocoder** [comment]
This relation is for saving only. There will never be an «implicit» delete.

**Comment by allain** [comment]
If this is the intent of the extension, it ought to explicitly say so in the readme since this differs greatly from how many users (including myself) expect it to behave.

**Comment by creocoder** [comment]
This will be done, but a little differently and without side effects.

**Comment by creocoder** [comment]
```
<?php
$post->tags=array();
$post->withRelated->save(true,array('tags'));
```

should NOT clear all relations.

Me with some members of yiiext team discuss it before i designed this extension. Very very long time ago. It was known even before writing the first line of code.

**Comment by allain** [comment]
Fair enough. I didn't think that it was an oversight. Glad to know that it's been thought through.

Until the new and improved version that does explicit deletes is released, I'm not sure this behaviour is well understood.

Anyway, thanks for this useful extension.
